{% extends 'base.phtml' %}
{% block title %}About Us{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h1>About Us</h1>
    <p>
      GameBantons™ is an online game store that provides a simple and convenient shopping experience to all gamers.
      We provide video games of many genres along with its respective consoles. We also offer the latest gaming accessories
      to make your online gaming experience one you won't forget. 
      
      We also provide deals and discounts on products storewide to our platinum members. 
      So sign up today for your membership and unleash the gamer in you!
      
    </p>
    <h4>Contact Us</h4>
    <a href="#">Facebook</a>
    <a href="#">Google+</a>
  </div>

</div>
{% endblock %}
