{% extends 'base.phtml' %}
{% block title %}Home{% endblock %}
{% block content %}
{% block info %}
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h1>Hello, this is the HomePage</h1>
     <?php
          function connectDB(){
  try{
    $db = new mysqli("us-cdbr-iron-east-04.cleardb.net","bee11f4e479155","07064880","heroku_f154ae20fe9c574");//Change later
    if($db == NULL && $db->connect_errno > 0)return NULL;
    return $db;
  }catch(Exception $e){}
  return NULL;
}
          $db = connectDB();
         if ($db == NULL) echo "did not work";
          else 
            echo "did work";
          ?>
  </div>
</div>
{% endblock %}
<div class="row" ng-app="project">
  <div class="col-md-10 col-md-offset-1">
    <div class="col-sm-8">
      <div class="btn-group btn-group-justified" role="group">
        <a class="btn btn-default" href="#/games">Games</a>
        <a class="btn btn-default" href="#/consoles">Consoles</a>
        <a class="btn btn-default" href="#/acc">Accessories</a>
      </div>
      <div ng-view>
      </div>
      <h3>We are the Best!</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-body">
          <h2>Login</h2>
          <form action="/user" method="post" onsubmit="return valLogin();"id="login">
            <div class="form-group">
              <label for="username">Username</label>
              <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" id="password" name="password">
            </div>
            <div class="form-group">
              <label for="usertype">Usertype</label>
              <select class="form-control"name="usertype" id="usertype">
                <option value="9">Select User Type</option>
                <option value="0">0</option>
                <option value="1">1</option>
              </select>
            </div>
            <div class="form-group">
              <button class="btn btn-primary"type="submit" name="submit">Login!</button>
            </div>
          </form>
          <p>Need an Account? <a href="/test/signup">Sign Up!</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class=" col-md-10 col-md-offset-1">
    <h3>Latest Deals</h3>
    <div class="row">
  <div class="col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="res/images/logo.png" alt="Logo" style="width:10%">
        <div class="caption">
          <p>Lorem ipsum...</p>
         
        </div>
      </a>
    </div>
  </div>
  <div class="col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="res/images/logo.png" alt="Logo" style="width:10%">
        <div class="caption">
          <p>Lorem ipsum...</p>
        </div>
      </a>
    </div>
  </div>
  <div class="col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="res/images/logo.png" alt="Logo" style="width:10%">
        <div class="caption">
          <p>Lorem ipsum...</p>
        </div>
      </a>
    </div>
  </div>
  <div class="col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="res/images/logo.png" alt="Logo" style="width:10%">
        <div class="caption">
          <p>Lorem ipsum...</p>
        </div>
      </a>
    </div>
  </div>
</div>

  </div>
</div>
{% endblock %}
